### PR TITLE
Resolved version conflict with maven-core

### PR DESCRIPTION
**Pull request by jruaux**
maven-core 3.8.6 depends on maven-resolver-* 1.6.3. This should solve the AbstractMethodError (issue #6)

### CODE REVIEW

**Comment by aalmiray** [comment]
I think pomchecker recently upgraded to Maven 3.8.7

Going back to resolver 1.6.3 feels weird to me. I wonder if there's something else that can be done to fix the underlying issue.

**Comment by jruaux** [comment]
I added a dependency for maven-resolver-impl which was the one conflicting with other maven-resolver-* dependencies. Hopefully that does it.

**Comment by aalmiray** [comment]
Were you able to test it locally?

**Comment by aalmiray** [comment]
FWIW the Gradle plugin may need an update as well https://github.com/kordamp/pomchecker/tree/master/pomchecker-gradle-plugin

**Comment by jruaux** [comment]
Yes I tested locally and it works

**Comment by aalmiray** [comment]
Thanks! 😄

**Comment by jruaux** [comment]
> FWIW the Gradle plugin may need an update as well https://github.com/kordamp/pomchecker/tree/master/pomchecker-gradle-plugin

Does the gradle plugin need to have the same dependencies as pomchecker-core? Not sure how this works for maven-resolver-impl

**Comment by aalmiray** [comment]
Just posted an update https://github.com/kordamp/pomchecker/commit/224da687a70b2f6fe9cbcdab7acfa30ac8613205

**Pull request merged**
